// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package repository

import (
	"context"
)

const getVerifiedEmailBySSHIdentifier = `-- name: GetVerifiedEmailBySSHIdentifier :one
SELECT email
FROM public."user"
WHERE ssh_identifier = $1
  AND email_verified = true
`

func (q *Queries) GetVerifiedEmailBySSHIdentifier(ctx context.Context, sshIdentifier string) (string, error) {
	row := q.db.QueryRow(ctx, getVerifiedEmailBySSHIdentifier, sshIdentifier)
	var email string
	err := row.Scan(&email)
	return email, err
}
