// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Identifier struct {
	ID        uuid.UUID
	Slug      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
