// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package repository

import (
	"context"
)

const userExistsByIdentifier = `-- name: UserExistsByIdentifier :one
SELECT EXISTS (
    SELECT 1
    FROM public."user"
    WHERE identifier = $1
) AS exists
`

func (q *Queries) UserExistsByIdentifier(ctx context.Context, identifier string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsByIdentifier, identifier)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
